# Generated by Django 5.1.7 on 2025-12-04 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_attendancecorrection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='admin_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='new_password',
            field=models.CharField(default='temp123', max_length=128),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to='employees.employee'),
        ),
    ]
