# Generated by Django 5.1.7 on 2025-12-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_salarypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
