# Generated by Django 5.1.7 on 2025-12-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_jobapplication_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
