# Generated by Django 5.1.7 on 2025-12-13 03:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_theme_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['-given_at'], 'verbose_name_plural': 'Bonuses'},
        ),
        migrations.AlterModelOptions(
            name='salaryhistory',
            options={'ordering': ['-changed_at'], 'verbose_name_plural': 'Salary histories'},
        ),
        migrations.AlterModelOptions(
            name='salarypayment',
            options={'ordering': ['-year', '-month', '-created_at']},
        ),
        migrations.AddField(
            model_name='bonus',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='given_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_changes_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_executed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PayrollBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee_count', models.IntegerField(default=0)),
                ('successful_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_created', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payroll batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='employees.payrollbatch'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['status', 'month', 'year'], name='employees_s_status_555a36_idx'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['employee', 'status'], name='employees_s_employe_3374ff_idx'),
        ),
    ]
