# Generated by Django 5.1.7 on 2025-12-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_bonus_options_alter_salaryhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollbatch',
            name='approval_threshold',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='paid', max_length=20),
        ),
    ]
