# Generated by Django 5.1.7 on 2025-12-13 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_payrollbatch_approval_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=200)),
                ('account_number_encrypted', models.BinaryField()),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('routing_code', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('checking', 'Checking'), ('current', 'Current')], default='savings', max_length=20)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='unverified', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_method', models.CharField(blank=True, max_length=50)),
                ('verification_proof', models.TextField(blank=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankSubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_format', models.CharField(max_length=50)),
                ('file_content', models.TextField()),
                ('file_hash', models.CharField(max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('bank_confirmation', models.TextField(blank=True)),
                ('bank_file_id', models.CharField(blank=True, max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_files', to='employees.payrollbatch')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('bank_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('utr_number', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('submitted', 'Submitted to Bank'), ('accepted', 'Accepted by Bank'), ('processing', 'Processing'), ('settled', 'Settled'), ('returned', 'Returned'), ('failed', 'Failed')], default='prepared', max_length=20)),
                ('bank_account_snapshot', models.JSONField()),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('bank_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_transactions', to=settings.AUTH_USER_MODEL)),
                ('salary_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transaction', to='employees.salarypayment')),
            ],
            options={
                'ordering': ['-prepared_at'],
                'indexes': [models.Index(fields=['status', 'reconciled'], name='employees_b_status_2ce1b7_idx'), models.Index(fields=['bank_reference'], name='employees_b_bank_re_aa4800_idx')],
            },
        ),
    ]
